### PR TITLE
2022 01 05 arnwinej

### PR DESCRIPTION
**Pull request by arnwinej**
Contains edits to remaining msParts, as well as a theoretical palimpsest file; may require another palimpsest with which to merge in Wright's assessment

### CODE REVIEW

**Review by wlpotter — CHANGES_REQUESTED** [review]
@arnwinej These look good overall. I just sent you an email about encoding palimpsests. 381 looks great; 382 looks good it just needs a different URI as 382 is already taken. Please update that URI, file name, etc. and resubmit the pr. Let me know if you need further clarity on the palimpsest process.

Also, could you include in that pr a comment specifying the order in which the parts should appear? (it should be in folio sequence with the upper text appearing before the lower text). This is needed for the merge script to know the order of the msParts.

**Comment by wlpotter** [comment]
For reference, I've added some documentation of the palimpsest workflow: https://github.com/srophe/wright-catalogue/wiki/Workflow-for-Creating-Manuscript-Records-for-Palimpsest-Manuscripts. Let me know if it's helpful or confusing

**Review by arnwinej — COMMENTED** [review]
Changes made to palimpsestic MS; new URI created for 381 palimpsest; now 1487. Order of msParts should now be 379, 380, 381 (upper text), and 1487 (lower text).

**Comment by wlpotter** [comment]
@arnwinej did you mean to close this? The palimpsests look good, so I can pull this in and create the merged composite ms record unless you noticed something?

**Comment by wlpotter** [comment]
@arnwinej sounds good! You can either close the pull request (I just wasn't sure if that was on purpose or not) or mark it as draft. Either way works for me, so whichever is a better work flow for you, go with that.

**Comment by arnwinej** [comment]
@wlpotter All changes should now be finalized for this pull request. Let me know what you think. The order for the msParts of 378 should now be: 379, 380, 381 (upper text), and 1487 (lower text). As for 837, the order for these msParts should be: 1488 (upper text) and 1489 (lower text). Is this all the information you need for the merge?

**Review by wlpotter — APPROVED** [review]
These all look good!

**Pull request merged**
